version: "3.8"
services:
  llm-service:
    build: ./llm-service
    ports:
      - "8000:8000"
    environment:
      - MODE=mock

  go-api:
    build: ./go-api
    ports:
      - "8080:8080"
    depends_on:
      - llm-service
